# Generated by Django 6.1.1 on 2026-09-18 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('sigla', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orgao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
                ('sigla', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.TextField()),
                ('tipo', models.CharField(choices=[('ME', 'Múltipla Escolha'), ('CE', 'Certo/Errado')], default='ME', max_length=2)),
                ('ano', models.IntegerField()),
                ('banca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questoes.banca')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questoes.cargo')),
                ('orgao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questoes.orgao')),
            ],
        ),
        migrations.CreateModel(
            name='Alternativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('is_correta', models.BooleanField(default=False)),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternativas', to='questoes.questao')),
            ],
        ),
        migrations.CreateModel(
            name='ResolucaoOficial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('questao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resolucao', to='questoes.questao')),
            ],
        ),
        migrations.CreateModel(
            name='Topico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topicos', to='questoes.materia')),
            ],
        ),
        migrations.AddField(
            model_name='questao',
            name='topicos',
            field=models.ManyToManyField(related_name='questoes', to='questoes.topico'),
        ),
    ]
