# Generated by Django 6.1.1 on 2026-09-18 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questoes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoResolucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acertou', models.BooleanField()),
                ('data_resposta', models.DateTimeField(auto_now_add=True)),
                ('alternativa_escolhida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questoes.alternativa')),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='questoes.questao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
