# Generated by Django 6.1.1 on 2026-09-18 21:12

import django.db.models.deletion
from django.db import migrations, models


def preencher_ordem_alternativas(apps, schema_editor):
    Alternativa = apps.get_model('questoes', 'Alternativa')
    ultima_ordem = {}
    for alternativa in Alternativa.objects.order_by('questao_id', 'id'):
        ordem = ultima_ordem.get(alternativa.questao_id, 0) + 1
        ultima_ordem[alternativa.questao_id] = ordem
        Alternativa.objects.filter(pk=alternativa.pk).update(ordem=ordem)


class Migration(migrations.Migration):

    dependencies = [
        ('questoes', '0002_historicoresolucao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alternativa',
            options={'ordering': ['ordem', 'id']},
        ),
        migrations.AlterModelOptions(
            name='historicoresolucao',
            options={'ordering': ['-data_resposta'], 'verbose_name': 'histórico de resolução', 'verbose_name_plural': 'histórico de resoluções'},
        ),
        migrations.AlterModelOptions(
            name='questao',
            options={'ordering': ['-ano', 'id']},
        ),
        migrations.AlterModelOptions(
            name='topico',
            options={'ordering': ['materia__nome', 'nome']},
        ),
        migrations.AddField(
            model_name='alternativa',
            name='ordem',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        # Preenche a ordem das alternativas já existentes (1, 2, 3...) na ordem em que foram cadastradas
        migrations.RunPython(preencher_ordem_alternativas, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='historicoresolucao',
            name='alternativa_escolhida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questoes.alternativa'),
        ),
        migrations.AddConstraint(
            model_name='alternativa',
            constraint=models.UniqueConstraint(condition=models.Q(('is_correta', True)), fields=('questao',), name='uma_alternativa_correta_por_questao', violation_error_message='Esta questão já possui uma alternativa correta.'),
        ),
    ]
