# Generated by Django 6.1.1 on 2026-09-18 21:49

from django.db import migrations


def conceder_ao_grupo_administrador(apps, schema_editor):
    # O Django só cria as permissões novas depois de todas as migrações (sinal post_migrate),
    # por isso a permissão é criada aqui com get_or_create antes de ser dada ao grupo.
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Permission = apps.get_model('auth', 'Permission')
    Group = apps.get_model('auth', 'Group')

    tipo, _ = ContentType.objects.get_or_create(app_label='questoes', model='questao')
    permissao, _ = Permission.objects.get_or_create(
        codename='importar_questoes',
        content_type=tipo,
        defaults={'name': 'Pode importar questões por planilha CSV'},
    )
    # Só concede se o grupo existir (num banco novo ele ainda não foi criado)
    for grupo in Group.objects.filter(name='Administrador'):
        grupo.permissions.add(permissao)


def remover_do_grupo_administrador(apps, schema_editor):
    Permission = apps.get_model('auth', 'Permission')
    Group = apps.get_model('auth', 'Group')
    for grupo in Group.objects.filter(name='Administrador'):
        grupo.permissions.remove(*Permission.objects.filter(codename='importar_questoes'))


class Migration(migrations.Migration):

    dependencies = [
        ('questoes', '0003_alter_alternativa_options_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questao',
            options={'ordering': ['-ano', 'id'], 'permissions': [('importar_questoes', 'Pode importar questões por planilha CSV')]},
        ),
        migrations.RunPython(conceder_ao_grupo_administrador, remover_do_grupo_administrador),
    ]
