# Generated by Django 6.1.1 on 2026-09-18 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questoes', '0004_permissao_importar_questoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
