# Generated by Django 6.1.1 on 2026-09-18 22:33

import django.db.models.deletion
import django.db.models.functions.text
import django.db.models.lookups
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questoes', '0005_questao_codigo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(max_length=1000)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='questoes.questao')),
                ('resposta_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='questoes.comentario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'comentário',
                'verbose_name_plural': 'comentários',
                'ordering': ['data_criacao', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(django.db.models.lookups.GreaterThan(django.db.models.functions.text.Length('texto'), 0), django.db.models.lookups.LessThanOrEqual(django.db.models.functions.text.Length('texto'), 1000)), name='comentario_tamanho_valido')],
            },
        ),
    ]
