# Generated by Django 6.1.1 on 2026-09-18 23:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questoes', '0008_curtidas_resolucao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resolucaooficial',
            name='descurtidas',
            field=models.ManyToManyField(blank=True, related_name='resolucoes_descurtidas', to=settings.AUTH_USER_MODEL),
        ),
    ]
