# Generated by Django 6.1.1 on 2026-09-21 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questoes', '0009_descurtidas_resolucao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Simulado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('questoes', models.ManyToManyField(related_name='simulados', to='questoes.questao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em', '-id'],
            },
        ),
        migrations.AddField(
            model_name='historicoresolucao',
            name='simulado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolucoes', to='questoes.simulado'),
        ),
        migrations.AddConstraint(
            model_name='historicoresolucao',
            constraint=models.UniqueConstraint(condition=models.Q(('simulado__isnull', False)), fields=('simulado', 'questao'), name='uma_resposta_por_questao_no_simulado'),
        ),
    ]
